version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "2500:2500"  # ajuste a porta conforme necessário
    command: python3 main.py
    tty: true
